/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pedidos;

import BasedeDatos.Conexion;
import java.sql.ResultSet;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SABAGIP
 */
public class Pedido extends javax.swing.JFrame {

    Conexion conexion = new Conexion();
    String comandoSQL;
    ResultSet query;
    DefaultTableModel modelo = new DefaultTableModel();
    String numPedido;
    String nombreCliente;
    String atendiendo;
    String atendido;
    ImageIcon icon = new ImageIcon();
    Map iconos = new HashMap();
    JLabel etiqueta = new JLabel();
    Timer temp;
    int seg;
    JFrame ventana;

    /**
     * Creates new form pedido
     */
    public Pedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedido = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "# Pedido", "Cliente", "Atendiendo", "Atendido"
            }
        ));
        tblPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPedido);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        llenarTabla();
        temporizador(500, this);
        temp.start();
    }//GEN-LAST:event_formWindowActivated

    private void tblPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidoMouseClicked
        // TODO add your handling code here:
        int punto = 0;
        punto = tblPedido.rowAtPoint(evt.getPoint());
        if (punto > -1) {
            DetalleCompra.numeroPedido = String.valueOf(tblPedido.getValueAt(punto, 0));
            DetalleCompra.nombreCliente = String.valueOf(tblPedido.getValueAt(punto, 1));

            comandoSQL = "UPDATE compra SET atendiendo = 1 WHERE idcompra = " + String.valueOf(tblPedido.getValueAt(punto, 0));

            if (conexion.ejecutarSQL(comandoSQL)) {
                DetalleCompra detalleCompra = new DetalleCompra();
                detalleCompra.setVisible(true);
                this.dispose();
            }
        }


    }//GEN-LAST:event_tblPedidoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedido().setVisible(true);
            }
        });
    }

    void llenarTabla() {
        tblPedido.setDefaultRenderer(Object.class, new IconCellRenderer());
        Object arreglo[] = new Object[6];
        modelo = (DefaultTableModel) tblPedido.getModel();
        modelo.setRowCount(0);
        tblPedido.setRowHeight(60);

        if (conexion.crearConexion()) {
            comandoSQL = "SELECT idcompra, nombre_cliente, apellido_paterno_cliente, "
                    + "apellido_materno_cliente, atendiendo, atendido FROM compra WHERE "
                    + "( atendiendo = 0 AND atendido = 0 ) OR (atendiendo = 1 AND atendido = 0)";
            query = (ResultSet) conexion.ejecutarSQLSelect(comandoSQL);

            try {

                while (query.next()) {
                    for (int i = 0; i < arreglo.length; i++) {
                        arreglo[i] = query.getObject(i + 1);
                    }
                    nombreCliente = (String) arreglo[1] + " " + arreglo[2] + " " + arreglo[3];
                    arreglo[2] = arreglo[4];
                    arreglo[3] = arreglo[5];
                    arreglo[1] = nombreCliente;

                    if ((int) arreglo[2] == (int) 0) {
                        icon = new ImageIcon(getClass().getResource("/Imagenes/no.jpg"));
                        arreglo[2] = new JLabel(icon);

                        if ((int) arreglo[3] == (int) 0) {
                            icon = new ImageIcon(getClass().getResource("/Imagenes/no.jpg"));
                            arreglo[3] = new JLabel(icon);
                        }
                    } else {

                        if ((int) arreglo[2] == (int) 1) {
                            icon = new ImageIcon(getClass().getResource("/Imagenes/reloj.jpg"));
                            arreglo[2] = new JLabel(icon);

                            if ((int) arreglo[3] == (int) 0) {
                                icon = new ImageIcon(getClass().getResource("/Imagenes/no.jpg"));
                                arreglo[3] = new JLabel(icon);
                            }
                        }
                    }

                    modelo.addRow(arreglo);
                }
            } catch (Exception e) {
            }

        }

    }
    
    
    void temporizador(int segundos, JFrame frame) {
    
        temp = new Timer(segundos, new ActionListener() {
    

            @Override
            public void actionPerformed(ActionEvent e) {
                   llenarTabla();
               
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPedido;
    // End of variables declaration//GEN-END:variables
}
